<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>4fa30ef8-9eb6-4c2f-ad90-573f13359acd</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\src\Gateway.Api\Gateway.Api.csproj" />
      <ProjectReference Include="..\src\Shoppiness.ProductsService\Shoppiness.ProductsService.csproj" />
      <ProjectReference Include="..\src\Shoppiness.StocksService\Shoppiness.StocksService.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.Azure.ServiceBus" Version="13.4.6" />
      <PackageReference Include="Aspire.Hosting.Docker" Version="13.4.6" />
      <PackageReference Include="Aspire.Hosting.Keycloak" Version="13.4.6-preview.1.26319.6" />
      <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
      <PackageReference Include="Aspire.Hosting.Redis" Version="13.4.6" />
    </ItemGroup>

</Project>
